-- V4: Create experience table for the timeline section.
-- Uses structured DATE columns (not a formatted string) for future-safe sorting/filtering.
-- display_label provides the exact UI string without coupling the UI to date formatting.
-- tags are comma-separated display-only values (consistent with project.technologies pattern).

CREATE TABLE IF NOT EXISTS experience (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role          VARCHAR(120)  NOT NULL,
    company       VARCHAR(200)  NOT NULL,
    location      VARCHAR(80),
    start_date    DATE          NOT NULL,
    end_date      DATE,                    -- NULL when is_current = TRUE
    is_current    BOOLEAN       NOT NULL DEFAULT FALSE,
    display_label VARCHAR(80),             -- Optional UI override. If present, render verbatim.
                                           -- If NULL, format from start_date / end_date / is_current.
    description   VARCHAR(2000) NOT NULL,
    tags          VARCHAR(500),            -- DISPLAY-ONLY. Comma-separated. Not for query predicates.
    display_order INTEGER       NOT NULL DEFAULT 0,

    -- Enforce: current roles have no end date; past roles must have one.
    CONSTRAINT experience_date_check CHECK (
        (is_current = TRUE  AND end_date IS NULL)
     OR (is_current = FALSE AND end_date IS NOT NULL)
    )
);
