-- V5: Create principle table for the Engineering Principles section.
-- icon_key stores a string identifier (e.g. "file", "clock", "grid", "shield") mapped
-- to SVG definitions maintained in the frontend PRINCIPLE_ICONS constant.
-- Separation: content (DB) vs. presentation (frontend SVG lookup).

CREATE TABLE IF NOT EXISTS principle (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         VARCHAR(200)  NOT NULL,
    description   VARCHAR(1000) NOT NULL,
    icon_key      VARCHAR(40),             -- Maps to frontend SVG lookup. One of: file, clock, grid, shield.
    display_order INTEGER       NOT NULL DEFAULT 0
);
