-- V6: Create stat table for the About section stat cards.
-- value is stored as VARCHAR to accommodate display strings like "7+" and "2+".

CREATE TABLE IF NOT EXISTS stat (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value         VARCHAR(20)  NOT NULL,   -- e.g. "7+", "4", "2+"
    label         VARCHAR(100) NOT NULL,   -- e.g. "Projects shipped"
    display_order INTEGER      NOT NULL DEFAULT 0
);
